// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrainingApp.Data;

#nullable disable

namespace TrainingApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260425173419_AddExercisesAndWorkouts")]
    partial class AddExercisesAndWorkouts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("TrainingApp.Models.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("MuscleGroup")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Базовое упражнение на грудные мышцы",
                            MuscleGroup = "Грудь",
                            Name = "Жим лёжа"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Жим гантелей под углом 30-45 градусов",
                            MuscleGroup = "Грудь",
                            Name = "Жим гантелей на наклонной скамье"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Жим штанги под углом 30-45 градусов",
                            MuscleGroup = "Грудь",
                            Name = "Жим штанги на наклонной скамье"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Сведение рук с гантелями в стороны",
                            MuscleGroup = "Грудь",
                            Name = "Разводка гантелей лёжа"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Отжимания с акцентом на грудные мышцы",
                            MuscleGroup = "Грудь",
                            Name = "Отжимания на брусьях"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Сведение рук через тросы кроссовера",
                            MuscleGroup = "Грудь",
                            Name = "Сведение рук в кроссовере"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Растяжение грудных мышц и широчайших",
                            MuscleGroup = "Грудь",
                            Name = "Пуловер с гантелью"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Жим в тренажёре для грудных",
                            MuscleGroup = "Грудь",
                            Name = "Жим в тренажёре Хаммер"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Базовое упражнение на спину и ноги",
                            MuscleGroup = "Спина",
                            Name = "Становая тяга"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Тяга штанги к поясу в наклоне",
                            MuscleGroup = "Спина",
                            Name = "Тяга штанги в наклоне"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Тяга одной гантели с упором",
                            MuscleGroup = "Спина",
                            Name = "Тяга гантели в наклоне"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Подтягивания для широчайших",
                            MuscleGroup = "Спина",
                            Name = "Подтягивания широким хватом"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Тяга блока к груди",
                            MuscleGroup = "Спина",
                            Name = "Тяга верхнего блока"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Тяга блока к животу сидя",
                            MuscleGroup = "Спина",
                            Name = "Тяга горизонтального блока"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Разгибание спины на тренажёре",
                            MuscleGroup = "Спина",
                            Name = "Гиперэкстензия"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Подъём плеч со штангой",
                            MuscleGroup = "Спина",
                            Name = "Шраги со штангой"
                        },
                        new
                        {
                            Id = 17,
                            Description = "Тяга каната к лицу для задних дельт",
                            MuscleGroup = "Спина",
                            Name = "Face Pull (тяга к лицу)"
                        },
                        new
                        {
                            Id = 18,
                            Description = "Базовое упражнение на ноги",
                            MuscleGroup = "Ноги",
                            Name = "Приседания со штангой"
                        },
                        new
                        {
                            Id = 19,
                            Description = "Жим платформы ногами",
                            MuscleGroup = "Ноги",
                            Name = "Жим ногами"
                        },
                        new
                        {
                            Id = 20,
                            Description = "Шаги с гантелями",
                            MuscleGroup = "Ноги",
                            Name = "Выпады с гантелями"
                        },
                        new
                        {
                            Id = 21,
                            Description = "Разгибание ног сидя",
                            MuscleGroup = "Ноги",
                            Name = "Разгибание ног в тренажёре"
                        },
                        new
                        {
                            Id = 22,
                            Description = "Сгибание ног лёжа",
                            MuscleGroup = "Ноги",
                            Name = "Сгибание ног в тренажёре"
                        },
                        new
                        {
                            Id = 23,
                            Description = "Мёртвая тяга на прямых ногах",
                            MuscleGroup = "Ноги",
                            Name = "Румынская тяга"
                        },
                        new
                        {
                            Id = 24,
                            Description = "Икроножные мышцы",
                            MuscleGroup = "Ноги",
                            Name = "Подъёмы на носки"
                        },
                        new
                        {
                            Id = 25,
                            Description = "Приседания на одной ноге",
                            MuscleGroup = "Ноги",
                            Name = "Болгарские сплит-приседания"
                        },
                        new
                        {
                            Id = 26,
                            Description = "Подъём таза с весом",
                            MuscleGroup = "Ноги",
                            Name = "Ягодичный мостик"
                        },
                        new
                        {
                            Id = 27,
                            Description = "Жим штанги стоя/сидя",
                            MuscleGroup = "Плечи",
                            Name = "Армейский жим"
                        },
                        new
                        {
                            Id = 28,
                            Description = "Жим гантелей над головой",
                            MuscleGroup = "Плечи",
                            Name = "Жим гантелей сидя"
                        },
                        new
                        {
                            Id = 29,
                            Description = "Разведение гантелей через стороны",
                            MuscleGroup = "Плечи",
                            Name = "Махи гантелями в стороны"
                        },
                        new
                        {
                            Id = 30,
                            Description = "Разведение гантелей на задние дельты",
                            MuscleGroup = "Плечи",
                            Name = "Махи гантелями в наклоне"
                        },
                        new
                        {
                            Id = 31,
                            Description = "Тяга штанги к подбородку",
                            MuscleGroup = "Плечи",
                            Name = "Протяжка штанги"
                        },
                        new
                        {
                            Id = 32,
                            Description = "Подъём гантелей/штанги перед собой",
                            MuscleGroup = "Плечи",
                            Name = "Подъём рук перед собой"
                        },
                        new
                        {
                            Id = 33,
                            Description = "Махи в тренажёре",
                            MuscleGroup = "Плечи",
                            Name = "Разведение в стороны в тренажёре"
                        },
                        new
                        {
                            Id = 34,
                            Description = "Сгибание рук со штангой стоя",
                            MuscleGroup = "Бицепс",
                            Name = "Подъём штанги на бицепс"
                        },
                        new
                        {
                            Id = 35,
                            Description = "Сгибание рук с гантелями",
                            MuscleGroup = "Бицепс",
                            Name = "Подъём гантелей на бицепс"
                        },
                        new
                        {
                            Id = 36,
                            Description = "Подъём гантелей нейтральным хватом",
                            MuscleGroup = "Бицепс",
                            Name = "Молотки (Hammer Curls)"
                        },
                        new
                        {
                            Id = 37,
                            Description = "Изолированный подъём с упором",
                            MuscleGroup = "Бицепс",
                            Name = "Концентрированный подъём на бицепс"
                        },
                        new
                        {
                            Id = 38,
                            Description = "Сгибание рук на пюпитре",
                            MuscleGroup = "Бицепс",
                            Name = "Подъём на бицепс на скамье Скотта"
                        },
                        new
                        {
                            Id = 39,
                            Description = "Сгибание рук с нижнего блока",
                            MuscleGroup = "Бицепс",
                            Name = "Подъём на бицепс в кроссовере"
                        },
                        new
                        {
                            Id = 40,
                            Description = "Разгибание рук со штангой/гантелью",
                            MuscleGroup = "Трицепс",
                            Name = "Французский жим"
                        },
                        new
                        {
                            Id = 41,
                            Description = "Разгибание с верхнего блока",
                            MuscleGroup = "Трицепс",
                            Name = "Разгибание рук на блоке"
                        },
                        new
                        {
                            Id = 42,
                            Description = "Обратные отжимания",
                            MuscleGroup = "Трицепс",
                            Name = "Отжимания от скамьи сзади"
                        },
                        new
                        {
                            Id = 43,
                            Description = "Изолированное упражнение",
                            MuscleGroup = "Трицепс",
                            Name = "Разгибание руки с гантелью из-за головы"
                        },
                        new
                        {
                            Id = 44,
                            Description = "Жим лёжа узким хватом",
                            MuscleGroup = "Трицепс",
                            Name = "Жим узким хватом"
                        },
                        new
                        {
                            Id = 45,
                            Description = "Разгибание руки в наклоне",
                            MuscleGroup = "Трицепс",
                            Name = "Кикбэк с гантелью"
                        },
                        new
                        {
                            Id = 46,
                            Description = "Статическое упражнение на кор",
                            MuscleGroup = "Пресс",
                            Name = "Планка"
                        },
                        new
                        {
                            Id = 47,
                            Description = "Подъём корпуса лёжа",
                            MuscleGroup = "Пресс",
                            Name = "Скручивания"
                        },
                        new
                        {
                            Id = 48,
                            Description = "Подъём ног на перекладине",
                            MuscleGroup = "Пресс",
                            Name = "Подъём ног в висе"
                        },
                        new
                        {
                            Id = 49,
                            Description = "Косые скручивания",
                            MuscleGroup = "Пресс",
                            Name = "Велосипед"
                        },
                        new
                        {
                            Id = 50,
                            Description = "Повороты корпуса с весом",
                            MuscleGroup = "Пресс",
                            Name = "Русские скручивания"
                        },
                        new
                        {
                            Id = 51,
                            Description = "Статика на косые мышцы",
                            MuscleGroup = "Пресс",
                            Name = "Боковая планка"
                        },
                        new
                        {
                            Id = 52,
                            Description = "Бег в умеренном темпе",
                            MuscleGroup = "Кардио",
                            Name = "Бег на беговой дорожке"
                        },
                        new
                        {
                            Id = 53,
                            Description = "Кардио на эллипсоиде",
                            MuscleGroup = "Кардио",
                            Name = "Эллиптический тренажёр"
                        },
                        new
                        {
                            Id = 54,
                            Description = "Езда на велосипеде",
                            MuscleGroup = "Кардио",
                            Name = "Велотренажёр"
                        },
                        new
                        {
                            Id = 55,
                            Description = "Прыжки со скакалкой",
                            MuscleGroup = "Кардио",
                            Name = "Скакалка"
                        });
                });

            modelBuilder.Entity("TrainingApp.Models.Training", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Trainings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2026, 4, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Фокус: прогрессия в жиме\n\nОсновной блок:\n- Жим лёжа: 4×5 @ 87.5 кг (80%)\n- Жим гантелей наклонный: 3×8-10\n\nАксессуары:\n- Тяга штанги в наклоне: 4×8\n- Французский жим: 3×10-12\n- Face pull: 3×15-20\n- Планка: 3×45 сек",
                            DurationMinutes = 70,
                            Title = "Понедельник - Тяжёлый жим"
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2026, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Фокус: низ тела + верхняя добивка\n\nОсновной блок:\n- Приседания: 4×4 @ 110 кг (85%)\n- Тяга сумо (техника): 4×5 @ 80-90 кг\n\nАксессуары:\n- Армейский жим: 3×8-10\n- Махи в стороны: 3×12-15\n- Молотки: 3×10-12\n- Гиперэкстензия: 3×12",
                            DurationMinutes = 80,
                            Title = "Среда - Присед + Тяга сумо"
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Фокус: скорость, техника\n\nОсновной блок:\n- Жим лёжа (скоростной): 6×3 @ 77.5 кг\n- Жим лёжа (пауза): 3×5 @ 82.5 кг\n\nАксессуары (суперсеты):\n- Отжимания на брусьях + Тяга гантели\n- Разводка + Молотки\n- Пресс: 3×15",
                            DurationMinutes = 80,
                            Title = "Пятница - Скоростной жим"
                        });
                });

            modelBuilder.Entity("TrainingApp.Models.WorkoutExercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Reps")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sets")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrainingId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("WeightKg")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("TrainingId");

                    b.ToTable("WorkoutExercises");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExerciseId = 1,
                            Notes = "80% от максимума, пауза на груди",
                            Order = 1,
                            Reps = 5,
                            Sets = 4,
                            TrainingId = 1,
                            WeightKg = 87.5
                        },
                        new
                        {
                            Id = 2,
                            ExerciseId = 2,
                            Notes = "Наклон 30 градусов",
                            Order = 2,
                            Reps = 10,
                            Sets = 3,
                            TrainingId = 1,
                            WeightKg = 22.0
                        },
                        new
                        {
                            Id = 3,
                            ExerciseId = 10,
                            Notes = "Тяга к поясу",
                            Order = 3,
                            Reps = 8,
                            Sets = 4,
                            TrainingId = 1,
                            WeightKg = 60.0
                        },
                        new
                        {
                            Id = 4,
                            ExerciseId = 40,
                            Notes = "Французский жим",
                            Order = 4,
                            Reps = 12,
                            Sets = 3,
                            TrainingId = 1,
                            WeightKg = 30.0
                        },
                        new
                        {
                            Id = 5,
                            ExerciseId = 17,
                            Notes = "Face pull с канатом",
                            Order = 5,
                            Reps = 20,
                            Sets = 3,
                            TrainingId = 1
                        },
                        new
                        {
                            Id = 6,
                            ExerciseId = 46,
                            Notes = "45 секунд",
                            Order = 6,
                            Reps = 1,
                            Sets = 3,
                            TrainingId = 1
                        },
                        new
                        {
                            Id = 7,
                            ExerciseId = 18,
                            Notes = "85% от максимума",
                            Order = 1,
                            Reps = 4,
                            Sets = 4,
                            TrainingId = 2,
                            WeightKg = 110.0
                        },
                        new
                        {
                            Id = 8,
                            ExerciseId = 9,
                            Notes = "Техника сумо",
                            Order = 2,
                            Reps = 5,
                            Sets = 4,
                            TrainingId = 2,
                            WeightKg = 85.0
                        },
                        new
                        {
                            Id = 9,
                            ExerciseId = 27,
                            Notes = "Армейский жим стоя",
                            Order = 3,
                            Reps = 10,
                            Sets = 3,
                            TrainingId = 2,
                            WeightKg = 45.0
                        },
                        new
                        {
                            Id = 10,
                            ExerciseId = 29,
                            Notes = "Махи в стороны",
                            Order = 4,
                            Reps = 15,
                            Sets = 3,
                            TrainingId = 2,
                            WeightKg = 10.0
                        },
                        new
                        {
                            Id = 11,
                            ExerciseId = 36,
                            Notes = "Молотки",
                            Order = 5,
                            Reps = 12,
                            Sets = 3,
                            TrainingId = 2,
                            WeightKg = 16.0
                        },
                        new
                        {
                            Id = 12,
                            ExerciseId = 15,
                            Notes = "Гиперэкстензия с диском",
                            Order = 6,
                            Reps = 12,
                            Sets = 3,
                            TrainingId = 2,
                            WeightKg = 20.0
                        },
                        new
                        {
                            Id = 13,
                            ExerciseId = 1,
                            Notes = "Скоростной жим, максимальная скорость",
                            Order = 1,
                            Reps = 3,
                            Sets = 6,
                            TrainingId = 3,
                            WeightKg = 77.5
                        },
                        new
                        {
                            Id = 14,
                            ExerciseId = 1,
                            Notes = "Пауза 2 секунды на груди",
                            Order = 2,
                            Reps = 5,
                            Sets = 3,
                            TrainingId = 3,
                            WeightKg = 82.5
                        },
                        new
                        {
                            Id = 15,
                            ExerciseId = 5,
                            Notes = "Отжимания на брусьях",
                            Order = 3,
                            Reps = 10,
                            Sets = 3,
                            TrainingId = 3
                        },
                        new
                        {
                            Id = 16,
                            ExerciseId = 11,
                            Notes = "Тяга гантели",
                            Order = 4,
                            Reps = 10,
                            Sets = 3,
                            TrainingId = 3,
                            WeightKg = 30.0
                        },
                        new
                        {
                            Id = 17,
                            ExerciseId = 4,
                            Notes = "Разводка гантелей",
                            Order = 5,
                            Reps = 12,
                            Sets = 3,
                            TrainingId = 3,
                            WeightKg = 14.0
                        },
                        new
                        {
                            Id = 18,
                            ExerciseId = 47,
                            Notes = "Скручивания на пресс",
                            Order = 6,
                            Reps = 15,
                            Sets = 3,
                            TrainingId = 3
                        });
                });

            modelBuilder.Entity("TrainingApp.Models.WorkoutExercise", b =>
                {
                    b.HasOne("TrainingApp.Models.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TrainingApp.Models.Training", "Training")
                        .WithMany()
                        .HasForeignKey("TrainingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Training");
                });
#pragma warning restore 612, 618
        }
    }
}
